module.exports = {
	EAS_PROJECT_OWNER: "",
	EAS_PROJECT_ID: "",
	APPWRITE_ENDPOINT: "https://cloud.appwrite.io/v1",
	APPWRITE_PROJECT_ID: "",
	VERCEL_DEV_ENDPOINT: "http://localhost:2023/api",
	VERCEL_PROD_ENDPOINT: "",
	APPWRITE_DATABASE_ID: "",
	APPWRITE_BOOKMARK_COLLECTION_ID: "",
	APPWRITE_FOLDER_COLLECTION_ID: "",
	CLERK_PUBLISHABLE_KEY: "",
};
